name: Bump version

on:
  workflow_dispatch:
  push:
    branch:
      - main

permissions:
  content: write
  pull-request: write

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple