name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Set up GKE kubectl
      run: |
        gcloud container clusters get-credentials teste-mb --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    # Deploy do Helm Chart no GKE
    - name: Deploy Helm Chart to GKE
      run: |
        helm upgrade --install hello-world ./hello-world --namespace default --set image.tag=${{ github.ref_name }} --wait

    - name: Verify deployment success
      run: |
          kubectl rollout status deployment/hello-world --namespace default --timeout=5m
          kubectl get pods --namespace default -l app=hello-world -o custom-columns=":status.phase"
          kubectl get pods --namespace default -l app=hello-world --field-selector=status.phase!=Running --field-selector=status.phase!=Succeeded