name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up GKE kubectl
      run: gcloud container clusters get-credentials teste-mb --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Deploy Helm Chart to GKE
      run: |
        helm upgrade --install hello-world ./hello-world --namespace default --set image.tag=${{ github.ref_name }} --wait

    - name: Verify deployment success
      run: |
        kubectl rollout status deployment/hello-world --namespace default --timeout=5m

    - name: Undo deployment if fails
      if: failure()
      run: |
        kubectl undo deployment/hello-world --namespace default --timeout=5m