name: CI/CD

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-world-node:${{ github.ref_name }} .

    - name: Scan Docker image with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/project \
         aquasec/trivy image --exit-code 1 --no-progress --severity HIGH,CRITICAL ${{ secrets.DOCKER_USERNAME }}/hello-world-node:${{ github.ref_name }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/hello-world-node:${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
  
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Authenticate GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up GKE kubectl
      run: gcloud container clusters get-credentials teste-mb --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Deploy Helm Chart to GKE
      run: |
        helm upgrade --install hello-world ./hello-world --namespace default --set image.tag=${{ github.ref_name }} --wait

    - name: Verify deployment success
      run: |
        kubectl rollout status deployment/hello-world --namespace default --timeout=5m

    - name: Undo deployment if fails
      if: failure()
      run: |
        kubectl undo deployment/hello-world --namespace default --timeout=5m